Serial number: InternetGatewayDevice.DeviceInfo.SerialNumber
Product class: InternetGatewayDevice.DeviceInfo.ProductClass
ModelName: VirtualParameters.ModelName
Software version: InternetGatewayDevice.DeviceInfo.SoftwareVersion
MAC: VirtualParameters.MACAddress
IP: InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ExternalIPAddress
