Serial number: InternetGatewayDevice.DeviceInfo.SerialNumber
Product class: InternetGatewayDevice.DeviceInfo.ProductClass
ModelName: VirtualParameters.ModelName
Software version: InternetGatewayDevice.DeviceInfo.SoftwareVersion
MAC: VirtualParameters.MACAddress
TR069 Mgmt IP: VirtualParameters.TR069MgmtIp
Service ID: VirtualParameters.ProvisioningCode
